version: '3.9'
services:
  server:
    build: 
      context: ./Server
      dockerfile: dockerfiles/Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - SPORTS_ODDS_API_KEY=${SPORTS_ODDS_API_KEY}

  test:
    build:
      context: ./Server
      dockerfile: dockerfiles/Dockerfile.test
    environment:
      - SPORTS_ODDS_API_KEY=${SPORTS_ODDS_API_KEY}

  client:
    build:
      context: ./Client/ParsingPointsClient
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - API_URL=https://parsing-server-e2gdd0g5bycahwgd.eastus-01.azurewebsites.net


