name: build-and-test

env:
    AZURE_WEBAPP_NAME: parsing-points

on:
    push:
        branches: [fullStack]
    pull_request:
        branches: [main]
    workflow_dispatch:


jobs:
    build-and-test:
      runs-on: ubuntu-latest

      steps:
        - name: Check out repo
          uses: actions/checkout@v3

        - name: Convert repo owner to lowercase
          run: |
            echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
        
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
              
        - name: Login to Github Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GHCR_TOKEN }}

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

        - name: Build and push server image
          uses: docker/build-push-action@v4
          with:
            context: ./Server/
            file: ./Server/dockerfiles/Dockerfile.api
            push: true
            tags: docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/parsing-points-server:latest
            build-args: SPORTS_ODDS_API_KEY=${{ secrets.SPORTS_ODDS_API_KEY }}
            cache-from: type=registry,ref=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/parsing-points-server:cache
            cache-to: type=registry,ref=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/parsing-points-server:cache,mode=max

        - name: Build and push server test
          uses: docker/build-push-action@v4
          with:
            context: ./Server/
            file: ./Server/dockerfiles/Dockerfile.test
            push: true
            tags: docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/server-test:latest
            build-args: SPORTS_ODDS_API_KEY=${{ secrets.SPORTS_ODDS_API_KEY }}
            cache-from: type=registry,ref=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/server-test:cache
            cache-to: type=registry,ref=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/server-test:cache,mode=max

        - name: Build and push Angular client
          uses: docker/build-push-action@v4
          with:
            context: ./Client/ParsingPointsClient
            file: ./Client/ParsingPointsClient/Dockerfile
            push: true
            tags: docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/client:latest
            cache-from: type=registry,ref=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/client:cache
            cache-to: type=registry,ref=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/client:cache,mode=max

        - name: Cache Docker Compose
          uses: actions/cache@v3
          with:
            path: /usr/local/bin/docker-compose
            key: ${{ runner.os }}-docker-compose-${{ hashFiles('**/docker-compose.yml') }}
            restore-keys: |
              ${{ runner.os }}-docker-compose-

        - name: Install Docker Compose
          run: |
            if ! command -v docker-compose &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker-compose
            fi
        
        - name: Run Server Mock Tests
          run: |
            echo "SPORTS_ODDS_API_KEY=${{ secrets.SPORTS_ODDS_API_KEY }}"
            docker-compose run -e SPORTS_ODDS_API_KEY=${{ secrets.SPORTS_ODDS_API_KEY }} test

        