name: build-and-test

env:
    AZURE_WEBAPP_NAME: parsing-points

on:
    push:
        branches: [fullStack]
    pull_request:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build-and-test:
      runs-on: ubuntu-latest

      steps:
        - name: Check out repo
          uses: actions/checkout@v3

        - name: Convert repo owner to lowercase
          run: |
            echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
        
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
              
        - name: Login to Github Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GHCR_TOKEN }}

        - name: Build and push server image
          uses: docker/build-push-action@v4
          with:
            context: ./Server/
            file: ./Server/dockerfiles/Dockerfile.api
            push: true
            tags: ghcr.io/${{ env.REPO }}/parsing-points-server:latest
            build-args: SPORTS_ODDS_API_KEY=${{ secrets.SPORTS_ODDS_API_KEY }}

        - name: Build and push server test
          uses: docker/build-push-action@v4
          with:
            context: ./Server/
            file: ./Server/dockerfiles/Dockerfile.test
            push: true
            tags: ghcr.io/${{ env.REPO }}/server-test:latest
            build-args: SPORTS_ODDS_API_KEY=${{ secrets.SPORTS_ODDS_API_KEY }}
        
        - name: Run Server Mock Tests
          run: |
            cd Server
            sudo docker --version
        
        - name: Set publish profile as environment variable
          run: |
            echo "PUBLISH_PROFILE=${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" >> "${GITHUB_ENV}"

        - name: Print the publish profile for debugging
          run: |
            echo "Publish profile contents:"
            echo ${{ env.PUBLISH_PROFILE }}

    deploy:
      permissions:
        contents: none
      runs-on: ubuntu-latest
      needs: build-and-test
      environment:
        name: 'Development'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Lowercase the repo name and username
          run: |
            echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: $ {{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            images: 'ghcr.io/${{ env.REPO }}/parsing-points-server:latest'


